{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: microdrop.dmf-device-ui-plugin
  version: {{ GIT_VERSION }}

build:
  number: 0
  script: python -m mpm.bin.build

requirements:
  build:
    #: ..versionchanged:: 2.3.1
    #: ..versionchanged:: 2.3.2
    #: ..versionchanged:: 2.3.4
    #: ..versionchanged:: 2.4
    #: ..versionchanged:: X.X.X
    - dmf-device-ui >=0.11
    #: ..versionchanged:: 2.3.4
    #: ..versionchanged:: 2.4.1
    - microdrop >=2.17
    - microdrop-plugin-manager >=0.17
    - pandas
    - path_helpers >=0.2.post3
    #: ..versionadded:: 2.3.1
    - psutil >=5.4.0
    - pyyaml
    - si-prefix >=0.4.post10

  run:
    #: ..versionchanged:: 2.3.1
    #: ..versionchanged:: 2.3.2
    #: ..versionchanged:: 2.3.4
    #: ..versionchanged:: 2.4
    #: ..versionchanged:: X.X.X
    - dmf-device-ui >=0.11
    #: ..versionchanged:: 2.3.4
    #: ..versionchanged:: 2.4.1
    - microdrop >=2.17
    - microdrop-plugin-manager >=0.17
    - pandas
    #: ..versionadded:: 2.3.1
    - psutil >=5.4.0
    - path_helpers >=0.2.post3
    - pyyaml
    - si-prefix >=0.4.post10

test:
  commands:
    - python -m mpm.bin.import_test -a {{ PKG_NAME }}

about:
  home: https://github.com/sci-bots/{{ PKG_NAME }}
  license: BSD
